### ISSUE TITLE
Watch does not work with large result sets

### ISSUE THREAD

**Issue by smartrevolution** [zabawaba99/firego#15]
Hi,

in your eventSplit() function your are not handling the case, if the scanner doesn't find a '\n' at the end. Which can happen, when the results sets are bigger. But fixing that does not work either, because with larger result sets you can even run into a case where the scan exceeds MaxScanTokenSize. One way  to fix it, is to use bufio#Reader.ReadLine(). Do you want to fix it yourself or would you accept my patch for it?

BTW: Thanks for publishing the code. :)

Stefan

**Comment by zabawaba99** [comment]
We are always open to Pull Requests! I would just ask that you add a test (if you haven't already) for it so we can make sure it doesn't break again.

**Comment by smartrevolution** [comment]
Okay. Will create a Pull-Request on the weekend with a test. ;)

**Comment by zabawaba99** [comment]
Looking forward to it :dancers:

**Comment by Tonkpils** [comment]
Going to close this since #16 was merged.
