### ISSUE TITLE
Support for different params per Reference

### ISSUE THREAD

**Issue by crystalin** [zabawaba99/firego#26]
At the moment, the params are shared for all the references to the Firebase object.
Ex:
refA = fb.Child("/first_node")
refB = fb.Child("/another_node")

refA.Shallow(true) will also set shallow param to refB

**Comment by zabawaba99** [comment]
Thanks for catching that! Confirmed the issue with

``` go
func TestChild_Issue26(t *testing.T) {
    parent := New(URL)
    child1 := parent.Child("one")
    child2 := child1.Child("two")

    child1.Shallow(true)
    assert.Len(t, child2.params, 0)
}
```
