### ISSUE TITLE
Filtering using OrderBy does not working

### ISSUE THREAD

**Issue by keuller** [zabawaba99/firego#37]
Hi guys,

I'm trying to filter some data using the strategy "by a specified child key" as Firebase documentation shows. But its not working for me. Here is my code:

``` go
    courses := ref.Child("courses").OrderBy("author").StartAt(author)
    fmt.Println(courses.String())
    result := make(map[string]Course, 0)
    courses.Value(&result)
    return result
```

When I try to view the URL which Firego tries to connect (through .String() method) I just see that: **https://[domain].firebaseio.com/courses** instead of **https://[domain].firebaseio.com/courses.json?orderBy="author"** as shown by Firebase documentation.

Anyone can help me ?

**Comment by zabawaba99** [comment]
Hi @keuller I see what the issue is. It looks like when we copy the firebase reference we are not copying over the parameters that we use. It also seems a little weird that we are copying the reference for every query.

**Comment by zabawaba99** [comment]
I won't be able to get to this until later tonight or tomorrow morning, but I can review a PR in the meantime if you'd like to fix it.

**Comment by keuller** [comment]
Actually @zabawaba99 the error is different, although Firego does not show the correct URL, it is making a correct call. But I think Firego does not encoding correct the URL, because I'm getting this error.

``` json
{
  "error" : "orderBy must be a valid JSON encoded path"
}
```

But I suggest improve the .String() method to show off the parameters defined.

**Comment by keuller** [comment]
Hi @zabawaba99 I've solved the problem. In fact, the orderBy must be inside double quotes. I'll make a PR to Firego. I also changed the String() method to improve the visibility the URL with their respective parameters.
I've seen in your tests that you pass an argument using double quote to OrderBy method. But it is repetitve and very ugly, you can improve the OrderBy method to put those double quotes automatically, because its mandatory to Firebase service. I cancelled my PR because tests fail and I'll fix it.
