### ISSUE TITLE
support for storage

### ISSUE THREAD

**Issue by mattetti** [zabawaba99/firego#49]
this is a feature request

**Comment by zabawaba99** [comment]
Are you referring to https://firebase.google.com/docs/storage ?

**Comment by mattetti** [comment]
@zabawaba99 yes exactly. Main main use case is to push binary data such as images.

**Comment by jondot** [comment]
@mattetti I had a specific requirement for this. While reverse-engineering the Firebase API, I got to this solution https://github.com/jondot/firebase-simple-storage

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
