### ISSUE TITLE
how to check Token expire?

### ISSUE THREAD

**Issue by elvis-hp** [zabawaba99/firego#52]
I want auto gen token but i don't know how to check Token expire?
thanks

**Comment by zabawaba99** [comment]
There is currently no builtin way to check if a token has expired. Would you mind giving me a sample snippet of how you would see something like this working? From my understanding it would look something like

``` go
token := generateToken()
fb := firego.New("foo")
fb.Auth(token)
if fb.AuthExpired() {
    // do something
}
```

**Comment by elvis-hp** [comment]
Yes.
However, it is running on real time, where do we can check?
For example: token will expire around 1 hour, but my system run 24/24, so, 2nd time onwards, the system will not work? the code above can solve this? thank you.

**Comment by elvis-hp** [comment]
```
func () startFirebase() {
    f := firego.New(url, nil)
    f.Auth(token)
    notifications := make(chan firego.Event)
    if err := f.Watch(notifications); err != nil {
        log.Println(err)
    }
    for event := range notifications {
        if event.Type == firego.EventTypeError {
            log.Print("Error occurred, loop ending")
            new_token := generateToken(uid, secrect_key)
            log.Print("Stop Watching")
            f.StopWatching();
            log.Print("Strat Watching")
            startFirebase();
        } else { 
            ....
    }
}
```

**Comment by zabawaba99** [comment]
I understand what you're looking for. The auth token being revoked is actually being ignored right now ([chunk of code](https://github.com/zabawaba99/firego/blob/master/watch.go#L177)). We can make it so that an event is returned with a `firego.EventAuthRevoked` event type and have it close the connection since it is no longer valid.

**Comment by zabawaba99** [comment]
@hoangphuong now that #57 is merged you should be able to do

``` go
func () startFirebase() {
    f := firego.New(url, nil)
    f.Auth(token)
    notifications := make(chan firego.Event)
    if err := f.Watch(notifications); err != nil {
        log.Println(err)
    }
    for event := range notifications {
        if event.Type == firego.EventTypeAuthRevoked {
            log.Print("Auth expired")
            new_token := generateToken(uid, secrect_key)
            log.Print("Stop Watching")
            f.StopWatching();
            log.Print("Strat Watching")
            startFirebase();
        } else { 
            ....
    }
}
```
