### ISSUE TITLE
Race condition in StopWatching()

### ISSUE THREAD

**Issue by jlgale** [zabawaba99/firego#53]
It looks like it's not safe to have multiple callers to the `StopWatching()` method. Two back-to-back callers could both see `true` from `isWatching()` and then the second call would block forever on the `stopWatching` channel.

It would be fine if that was a rule: "don't call StopWatching() multiple times", but the go-routine started by `Watch()` actually calls `StopWatching()`, so the only way to avoid the race is to never call `StopWatching()` asynchronously?

**Comment by zabawaba99** [comment]
Thanks for creating the issue! Would you mind posting a code snippet to reproduce this issue to help visualize it a bit?

**Comment by jgeiger** [comment]
I don't have a code snippet, but I was running into this. It's a silent failure so it's hard to track down.

I had a single watcher per account, but I called StopWatching twice and it would hang randomly, but more frequently under load.

One call was a direct call "account.StopWatching" and the other was deferred "defer account.StopWatching"

Removing the explicit call seems to have fixed the issue, but I do believe there is still an issue.

**Comment by zabawaba99** [comment]
This _should_ have been fixed with the closing of #60 since it reworked the way the locks are used. I'm going to close the issue for now. If you see the issue happening again, please comment here or open up a PR.

**Comment by jlgale** [comment]
Thanks!
