### ISSUE TITLE
autoreconnect 

### ISSUE THREAD

**Issue by duyhtq** [zabawaba99/firego#54]
it looks like firego doesn't auto-reconnect AFTER the device lost internet for a long period and then got internet back again (say, after 30 mins).  how do you get around this so that firego client automatically reconnects after the device goes online again?  thanks.

**Comment by duyhtq** [comment]
here is the line in **watch.go** that got stuck forever if internet connection is lost.  is there a way to set timeout for scanner.ReadLine() or somehow throw an error if the internet connection no longer exists?

`evt, isPrefix, scanErr = scanner.ReadLine()
`

**Comment by zabawaba99** [comment]
> if the internet connection no longer exists?

I'm not too sure. I imagine would could make it so that it blows up after a certain amount of time.

---

If the internet comes back, does the function continue to process?

**Comment by duyhtq** [comment]
@zabawaba99 no... if the internet comes back up, it does nothing... its stuck at that line.

**Comment by rostopira** [comment]
When fix will be merged to master?

**Comment by zabawaba99** [comment]
Sorry for the delay, I haven't had too much time the past month. I will continue to work on this issue throughout the week.
