### ISSUE TITLE
runtime/cgo: pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by duyhtq** [zabawaba99/firego#55]
i keep running into this error in production.  it doesn't happen right away.  it only happens after running for about 10 hours.  i've been trying to debug it for a week without any success.  does anyone have this issue before?  any advice is much appreciated.

note: i'm running it on 32 bit arm board (raspberry pi or nvidia tegra k1).  i'm running the same code on my laptop / desktop and haven't seen any similar crash yet, but it may be just a matter of time that it will crash.

thanks.

runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb6dac926 m=264
goroutine 0 [idle]:
goroutine 0 [idle]:
goroutine 8 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:192 +0x4 fp=0x10925764 sp=0x10925760
runtime.goready(0x109628f0, 0x0)
        /usr/local/go/src/runtime/proc.go:274 +0x34 fp=0x10925778 sp=0x10925764
runtime.goroutineReady(0x408f08, 0x109628f0, 0x0)
        /usr/local/go/src/runtime/time.go:82 +0x34 fp=0x10925788 sp=0x10925778
runtime.timerproc()
        /usr/local/go/src/runtime/time.go:196 +0x2ec fp=0x109257dc sp=0x10925788
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4 fp=0x109257dc sp=0x109257dc
created by runtime.addtimerLocked
        /usr/local/go/src/runtime/time.go:116 +0x1c4

goroutine 17 [syscall, 122 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4

goroutine 49 [IO wait]:
net.runtime_pollWait(0xb63d1148, 0x72, 0x10abc000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0x10960638, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(_pollDesc).WaitRead(0x10960638, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(_netFD).Read(0x10960600, 0x10abc000, 0x400, 0x400, 0x0, 0xb5390018, 0x1096c000)
        /usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(_conn).Read(0x1094e078, 0x10abc000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xc8
crypto/tls.(_block).readFromUntil(0x10d965a0, 0xb5398bc8, 0x1094e078, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:460 +0xc8
crypto/tls.(_Conn).readRecord(0x109741c0, 0x5c0917, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:562 +0x240
crypto/tls.(_Conn).Read(0x109741c0, 0x10bd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:939 +0x13c
net/http.noteEOFReader.Read(0xb63dba78, 0x109741c0, 0x10a066c4, 0x10bd2000, 0x1000, 0x1000, 0x3fe20, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1690 +0x5c
net/http.(_noteEOFReader).Read(0x10d94290, 0x10bd2000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(_Reader).Read(0x10d15d40, 0x10bd2000, 0x1000, 0x1000, 0x10bd8be4, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:197 +0x10c
net/http.(_body).readLocked(0x10bcf590, 0x10bd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:651 +0x94
net/http.(_body).Read(0x10bcf590, 0x10bd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:643 +0x118
net/http.(_bodyEOFSignal).Read(0x10bcf5c0, 0x10bd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1616 +0x20c
bufio.(_Reader).fill(0x10bd8f6c)
        /usr/local/go/src/bufio/bufio.go:97 +0x1c4
bufio.(_Reader).ReadSlice(0x10bd8f6c, 0x1096400a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:328 +0x264
bufio.(_Reader).ReadLine(0x10bd8f6c, 0x0, 0x0, 0x0, 0x109da000, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:357 +0x60
github.com/duyhtq/maya/firego.(_Firebase).Watch.func1(0x10c52000, 0x10a12f20, 0x109610c0)
        /home/ubuntu/gows/src/github.com/duyhtq/maya/firego/watch.go:148 +0x234
created by github.com/duyhtq/maya/firego.(*Firebase).Watch
        /home/ubuntu/gows/src/github.com/duyhtq/maya/firego/watch.go:246 +0x468

goroutine 47 [select, 122 minutes]:
net/http.(*persistConn).readLoop(0x10a06690)
        /usr/local/go/src/net/http/transport.go:1185 +0xbf0

goroutine 50 [chan receive, 122 minutes]:
github.com/duyhtq/maya/firego.(_Firebase).Watch.func1.1(0x10a12f20, 0x10d943a0, 0x10d94398, 0x10c52000)
        /home/ubuntu/gows/src/github.com/duyhtq/maya/firego/watch.go:124 +0x30
created by github.com/duyhtq/maya/firego.(_Firebase).Watch.func1
        /home/ubuntu/gows/src/github.com/duyhtq/maya/firego/watch.go:131 +0x144

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x2b14
r2      0x6
r3      0x326ff450
r4      0x326ff910
r5      0x326ff450
r6      0x0
r7      0x10c
r8      0x1
r9      0x0
r10     0x114e1d40
fp      0x720120
ip      0x10c
sp      0x326fead8
lr      0xb6dbaebf
pc      0xb6dac926
cpsr    0x20000030
fault   0x0
exit status 2

**Comment by zabawaba99** [comment]
After you using the `os/exec` package in your code?

**Comment by duyhtq** [comment]
nope, not at all.

**Comment by duyhtq** [comment]
this is what happened right before the crash, when i printed out the event type in watch.go.

2016/09/16 12:24:35 watch.go:189: Event Type: keep-alive
2016/09/16 12:24:35 watch.go:208: Watch Event: keep-alive
2016/09/16 12:25:05 watch.go:189: Event Type: keep-alive
2016/09/16 12:25:05 watch.go:208: Watch Event: keep-alive
2016/09/16 12:25:35 watch.go:189: Event Type: keep-alive
2016/09/16 12:25:35 watch.go:208: Watch Event: keep-alive
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb6dac926 m=264

**Comment by duyhtq** [comment]
@zabawaba99 my apology.  i just looked again and there is another piece of code (independent of my firego code) that runs in the background in its own goroutine and calls os.exec every once in a while for some repetitive / monitoring services.  what is the conflict between os.exec and firego?  and how do you recommend to avoid this?  thanks.

**Comment by zabawaba99** [comment]
@duyhtq I did some searching around and ran into [this comment](https://groups.google.com/forum/#!topic/golang-nuts/8gszDBRZh_4) where someone was having a similar issues. 

> I believe this can happen on GNU/Linux if your program uses cgo and if 
> thread A is in the Go runtime starting up a new thread B while thread 
> C is execing a program.  The underlying cause is that while one thread 
> is calling exec the Linux kernel will fail attempts by other threads 
> to call clone by returning EAGAIN.  (Look for uses of the in_exec 
> field in the kernel sources.) 

The `net` (used by firego) and `os/exec` package both use cgo. You should be able to compile your app with the `netgo` tag to remove cgo from the http package. That _might_ solve your problem. Another [comment](https://groups.google.com/d/msg/golang-nuts/8gszDBRZh_4/lhROTfN9TxIJ) in that thread mentioned that it solved there problem.

**Comment by duyhtq** [comment]
hey @zabawaba99 i rebuilt my code with "-tags netgo" but the same error still occurred after a few hours running.  it looks like netgo doesn't have any effect on this bug.  do you have any other thought on what the problem could be?  the only long running goroutine/thread i have is the Watch(notifications) function listening for changes from firebase.

note:  for the same code, i don't have any issues if i run on my laptop/desktop/server.  i only have this problem when i run it on 32 arm board (rasperry bi or nvidia tegra k1).  i'm installing go 1.7.1 arm on them.  and i did rebuild with -tags netgo.

**Comment by zabawaba99** [comment]
@duyhtq I'm not too sure what may be going on. We could have a bit more of a back and forth over the gophers slack ([invite link](https://invite.slack.golangbridge.org/) if you're not a part of it) to see if we can debug the issue together

You can find me under `zabawaba`

**Comment by zabawaba99** [comment]
@duyhtq you still facing this issue?

**Comment by Confuset** [comment]
iam receiving this same error message:
`runtime/cgo: pthread_create failed: Resource temporarily unavailable`
i realized that the temp on my raspberrypi3 is pretty high ~80°
so this could be a reason as well…have you checked that?
`/opt/vc/bin/vcgencmd measure_temp`

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
