### ISSUE TITLE
how do I authenticate with firebase v3?

### ISSUE THREAD

**Issue by varung** [zabawaba99/firego#56]
In the old firebase v2, I was able to generate a token, and auth with that. Is it possible to use the service json file that Google gives you with this library?

**Comment by zabawaba99** [comment]
Currently, you can not use the service json file to authenticate with `firego`. However, you can still using a legacy token to authenticate with firebase.

<img width="1184" alt="screen shot 2016-10-03 at 11 03 24 pm" src="https://cloud.githubusercontent.com/assets/2306786/19061418/883f3104-89be-11e6-8f6e-9cb8b44ca01e.png">

I do plan on adding support for the service json file (hopefully this weekend). I will keep your posted with any progress that I make.

**Comment by wolfgangmeyers** [comment]
Any progress on this? I don't even see the legacy token generator anymore in the firebase console.

**Comment by rockwotj** [comment]
Service Accounts tab has the secrets now, but moving to service accounts is important

**Comment by zabawaba99** [comment]
@wolfgangmeyers I have not been able to make any progress on this just yet. I had it slated for the next few weeks. However, I'm thinking that I will put that work into v2 of firego which (I'm hoping) will have a much more Firebase feel to it. 

Thanks for pointing that out @rockwotj

**Comment by m00sey** [comment]
What sort of help do you need?

This is how we use a Service Account (V3) to create a client to work with the admin sdk, with the current firego library.

Using:
`
"golang.org/x/oauth2"
"golang.org/x/oauth2/google"
`

```	
d, err := ioutil.ReadFile("our_service_account.json")
if err != nil {
    return nil, err
}

conf, err := google.JWTConfigFromJSON(d, "https://www.googleapis.com/auth/userinfo.email",
		"https://www.googleapis.com/auth/firebase.database")
if err != nil {
    return nil, err
}

return firego.New("https://you.firebaseio.com", conf.Client(oauth2.NoContext)), nil
```

We are currently developing new functionality using firego, more than happy to help out.

**Comment by zabawaba99** [comment]
Hey @m00sey sorry for not getting back to you earlier just wrapped up a cross country move. The solution you posted looks great and I'm going to add it to the readme for `firego.v1`. 

I was looking for some help integrating this into [firego.v2](https://github.com/zabawaba99/firego/tree/v2-unstable) (currently under development) where a user would pass the path of their service_account.json file and we would inject the authorization header for them on every request.

**Comment by jasonbcox** [comment]
@m00sey Your solution works great.  Thanks!

**Comment by belek** [comment]
I am not sure and need help, can I use @m00sey snippet to sign in with custom token?
https://firebase.google.com/docs/auth/admin/create-custom-tokens#sign_in_using_custom_tokens_on_clients

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
