### ISSUE TITLE
Push notifications?

### ISSUE THREAD

**Issue by IvRRimum** [zabawaba99/firego#61]
Does `firego` support making a push notifications?

**Comment by zabawaba99** [comment]
There is no support for sending push notifications. Unfortunately, there's no documented way of sending notifications since it's all currently done through the Firebase console. However, I would be wiling to discuss possible implementations if someone manages to get it to work.

**Comment by IvRRimum** [comment]
I will get back at you in a few weeks/month. I will have this kind of assignment.

**Comment by rostopira** [comment]
There is documented way to sending push notifications, but it's not part of REST API, so it should be a different library. Here it is https://github.com/edganiukov/fcm

**Comment by zabawaba99** [comment]
I'm working on a `v2` of `firego` that has an `fcm` package. You can checkout the `v2-unstable` package and use it if you'd like. Please note though that this branch is still under active development and that the API is not guaranteed to stay as is. I will close this issue as soon as the official v2 branch is created.

**Comment by IvRRimum** [comment]
I just wrote it myself( its just 1 http request ).
