### ISSUE TITLE
Prevent loop to crash when EventTypeError

### ISSUE THREAD

**Issue by fallais** [zabawaba99/firego#71]
Hello,

What is the best way to prevent the loop to make the program crash when receiving an EventTypeError message please ?

```
        // Watch
	notifications := make(chan firego.Event)
	err := firebase.Watch(notifications)
	if err != nil {
		shared.Log.Fatalln("Notifications have stopped because an error occured :", err)
	}
	defer firebase.StopWatching()

        // Parse the events
	for event := range notifications {
		helpers.ParseEvent(event)
	}
```

I my ParseEvent, if an EventTypeError  happen, I just display a message, but the program crashes anyway.

Regards.

**Comment by zabawaba99** [comment]
The reason the the loop exits is because the `.Watch` function closes the channel if there is an error. If you want to have a single loop that handles the error case you could probably do something like

```go
notifications := make(chan firego.Event)
err := firebase.Watch(notifications)
if err != nil {
    shared.Log.Fatalln("Notifications have stopped because an error occured :", err)
}
defer firebase.StopWatching()

// Parse the events
for {
    event, ok := <-notifications
    if !ok {
        shared.Log.Fatalln("Notifications have stopped")
    }
    switch event.Type {
    case firego.EventTypeError:
        // if we got an error recreate the notifications channel 
        notifications := make(chan firego.Event)
        if err := firebase.Watch(notifications); err != nil {
            shared.Log.Fatalln("Notifications have stopped because an error occured :", err)
        }
    default:
        helpers.ParseEvent(event)
    }
}
```

Please note though, that the code above is not very resilient since it will fail if you receive an error twice. However, you should be able to use a similar pattern to prevent the program from exiting where you handle the specific `firego.EventTypeError` event and recreate the notifications channel.

**Comment by fallais** [comment]
Hello,

Thanks a lot for the complete answer !

Actually, I handle the `firego.EventTypeError` in the helpers function ParseEvent, by only displaying a Logrus log message. I hardly think how I could recreate the notification channel in it..
If I well understand, the key point is that the notification channel must not die, so maybe I could make my ParseEvent return an `error` and if error is not nil then recreate the notifications channel as you did above ?

I really need it to be resilient as it is used as a FCM notification server. I can't "miss" an event.

Good day !

**Comment by zabawaba99** [comment]
@fallais That sounds like a perfectly good way of handling as well. You could also probably test that logic using a `httptest.Server` and closing the connection when you get a notification.

**Comment by zabawaba99** [comment]
@fallais did that answer your question?

**Comment by fallais** [comment]
@zabawaba99 yes thanks a lot ! :)

**Comment by fallais** [comment]
Hello,

In fact, I am not sure of why you need to close the channel in case of error..
Could you explain please ?

**Comment by fallais** [comment]
Hello,

Did you see my last message please ? :)

**Comment by zabawaba99** [comment]
Hey @fallais , sorry about not getting back to you earlier. The reason I see that we need to close the channel is to prevent writing to a closed channel. We could do something along the lines of

```go
select {
case c <- struct{}{}:
default:
	println("exited")
	return
}
```

in the `watch` function but then we don't know whether the consumer closed the channel or is just processing the previous message.

**Comment by zabawaba99** [comment]
Anything else on this issue @fallais ?

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
