### ISSUE TITLE
Timing out on Watch notifications

### ISSUE THREAD

**Issue by tjmcwiz** [zabawaba99/firego#72]
Is there an easy way to trace the firego package? I had the program working but recently starting hitting this error condition. 

New to golang and using the nest api so the issue is probably mine but was looking to better isolate and understand the issue - 30 seconds should be long enough but it's very possible that some of my libraries did change on an update of my system as well.

**Comment by zabawaba99** [comment]
Could you elaborate a little bit more on what is happening? I know that @jgeiger had to make some changes to this library to make it work with the `nestapi` and had forked those changes to https://github.com/jgeiger/nestapi

**Comment by jgeiger** [comment]
Nest's API servers are pretty unstable at times. I don't remember doing anything that deals with a watch in the nestapi code, but my app (which uses my nestapi) checks for timeouts and then re-connects on the failures.

**Comment by zabawaba99** [comment]
Is there anything else that I can help with @tjmcwiz ?

**Comment by zabawaba99** [comment]
I'm going to close this issue for now @tjmcwiz since there nothing that can be done at the moment. If anything comes up, please feel free to reopen the issue.
