### ISSUE TITLE
Numeric string escapes to int in query

### ISSUE THREAD

**Issue by jakubdal** [zabawaba99/firego#73]
Because type of *Firebase.EqualTo (and other querying functions) argument is string, request asking for value `"1234"` is the same as the request asking for `1234` - they are both numeric. However firebase treats them differently, and so it's impossible to make query for numeric string (for example `"1234"`).

**Comment by zabawaba99** [comment]
There is a [PR](https://github.com/zabawaba99/firego/pull/65) that addresses this issue. I just pinged the author to see if they can wrap up the missing items so that it can merged in. If it's not done by the end of the week, I'll work off that PR to get it merged in.

**Comment by vzsg** [comment]
I created a new PR #74 that starts from the current master, and adds the new functions next to the previous ones, instead of changing their behavior. Please review and merge if you find it worthy.

**Comment by zabawaba99** [comment]
Resolved by #74 which is now merged
