### ISSUE TITLE
Firebase.String() function produces weird URL

### ISSUE THREAD

**Issue by consulthys** [zabawaba99/firego#75]
The [`Firebase.String()` function](https://github.com/zabawaba99/firego/blob/master/firebase.go#L183-L190) produces an URL of the form `https://xyz.firebaseio.com/abc/.json`.

Even though it works, it should probably be better if this URL would look like `https://xyz.firebaseio.com/abc.json` instead. 

Thoughts?

**Comment by tqwewe** [comment]
Is what you were expecting the exact same url, just without the / before the .json at the end of the string?

**Comment by consulthys** [comment]
Yes, exactly, as depicted in my comment above.

**Comment by tqwewe** [comment]
I'm not sure if it is nessisary to change the function to remove the `/` from the url before `.json`.
In your program you could use something like the following code to replace the `/.json` to `.json` only if it is at the end of the url.
```go
url := "https://xyz.firebaseio.com/abc/.json"
url = regexp.MustCompile(`/.json($|\?)`).ReplaceAllString(url, ".json?")
url = strings.TrimSuffix(url, "?")
fmt.Println(url)
```
The reason why I replace it to `.json?` (with the ?) and trim it is to make sure it only replaces the `/.json` if it is at the end of the url or before any url variables (?foo=bar).

**Comment by consulthys** [comment]
Replacing on the client-side is not really an issue, I'm not really concerned with that. My initial comment was more in the sense that this `String()` function should produce a nice URL. I'm just not sure why it would ever make sense to have a `/` preceding the `.json` extension. Why do we have a `/` there to begin with?

**Comment by tqwewe** [comment]
Ah, I didn't see that it was hard coded in the [Firebase.String() function](https://github.com/zabawaba99/firego/blob/master/firebase.go#L183-L190). It's not a big deal and doesn't have any affect on the result other than it producing a nicer looking url. I agree it is useless to append "/.json" rather than ".json" to the url.
Maybe make a pull request with this change.

**Comment by zabawaba99** [comment]
@consulthys the `/` was being appended to the URL to account for the case where there is no path provided :

```
fb := firego.New("https://hello.firebaseio.com", nil)
```

Which would then produce `https://hello.firebaseio.com/.json` when calling `String`. Given that appending `/.json` versus `.json` results in the same firebase reference, I didn't see the need to have special logic to add a trailing slash or strip it. 

If you would like to make a PR to change the logic, I would not be opposed to it so long as it covers the edge case mentioned above.

**Comment by consulthys** [comment]
@zabawaba99 thanks for shedding some light on this. I perfectly understand. Time allowing, I might submit a PR soon. Stay tuned...

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
