### ISSUE TITLE
Add Auth Error Callback

### ISSUE THREAD

**Issue by jakubdal** [zabawaba99/firego#78]
"Unsupported type EOF(&errors.errorString{s:"EOF"})If you see this log please report an issue on https://github.com/zabawaba99/firego"

However because the message lacks in any informations about where is the problem, I cannot provide more data at least for now.

**Comment by zabawaba99** [comment]
So this message is logged from one of the `ChildEventFunc`s. Could you give me a little bit more detail on which of the `ChildX` functions you are using? Do you see this log often?

**Comment by jakubdal** [comment]
`ChildChanged`, seems like I get this error every time I run `ChildChanged` function. Function call looks as follow:

`err = msgClient.ChildChanged(func(data firego.DataSnapshot, previousChildKey string) {
		fmt.Printf("\n\nChild changed: %+#v, previousChildKey: %v\n\n", data, previousChildKey)
	})`

Where msgClient is `msgClient, err := c.firebase.Ref("messages/-KaSC-rJFCP-fuO9j_iz/")`, which is a valid reference.

**Comment by jakubdal** [comment]
Turns out this is how firego reacts when you pass invalid authentication token for authentication. Shall I close the issue?

**Comment by zabawaba99** [comment]
Thanks for digging into this @jakubdal. I'd like to reuse this issue to implement an auth error callback

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
