### ISSUE TITLE
Errors always return as EOF

### ISSUE THREAD

**Issue by jasonbcox** [zabawaba99/firego#82]
Whenever there is an error of any kind (including auth errors, similar to issue #78), I get the following event and then the watch channel closes:
firego.Event{Type:"event_error", Path:"", Data:(*errors.errorString)(0xc82000a160), rawData:[]uint8(nil)}

Printing out event.Data gives:
&errors.errorString{s:"EOF"}

This same EOF error occurs for 'permission denied' as well as missing indexOn errors.  The only way for me to differentiate between them is to execute the same request via cURL.

**Comment by zabawaba99** [comment]
Are these errors coming only from the `Event` channel from `.Watch`?

**Comment by jasonbcox** [comment]
Yes, this is the only Event received from the .Watch() channel before it closes.

**Comment by zabawaba99** [comment]
Closing issue as repository is being archived.
