### ISSUE TITLE
OrderBy example returns a Go map which does not preserve order

### ISSUE THREAD

**Issue by lucanaldini** [zabawaba99/firego#83]
The example in the README.md for the orderBy attribute deserialises the result into a map.
If the user needs to display the results in ascending order, he cannot rely on the map, since the ordering of the items retrieved when looping through it is not preserved.

**Comment by xStrom** [comment]
The official REST API documentation claims that [The REST API Returns Unsorted Results](https://firebase.google.com/docs/database/rest/retrieve-data). Thus I don't think we're actually losing any ordering information by using a map.

**Comment by lucanaldini** [comment]
You're perfectly right. It does say that. I guess i was just surprised by the fact you ask the API to sort the data and then you have to sort it again by yourself.
Wonder why an array was not used to return the results, which would have preserved the ordering.
Oh well. Closing this since it's invalid. Thanks
