### ISSUE TITLE
ChildAdded doesn't work with a big amount of children

### ISSUE THREAD

**Issue by DzyubSpirit** [zabawaba99/firego#90]
if a node has 700-1000 children or more there are no calls to add child handler function. However, if a number of children are 100-300 handler is called a number of children times. 
Children are light-weight objects with 5-6 simple type fields. In a rare number of times, I've got calls but not as many as the number of children. 
I think it isn't a problem of firebase because with nodejs sdk it works fine.

**Comment by DzyubSpirit** [comment]
Sorry, it was because of my mistake ^)

**Comment by zabawaba99** [comment]
Hey @DzyubSpirit , sorry that I didn't get back to your earlier - been a little busy. Would love to know a bit more about what happened. Anyway we could make the documentation a bit clearer?

**Comment by DzyubSpirit** [comment]
@zabawaba99, My problem was about using ```for {}``` instead of ```select {}``` after ```fb.ChildAdded()```. So main goroutine was too busy for handling big amount of events :)
Sorry, it's about my unfamiliarity with goroutines, documentation is great  :+1:
